@baseURL = http://localhost:8000
@apikey = {{$dotenv API_KEYS}}

# @name HealthCheck

GET {{baseURL}}/
xi-api-key: {{apikey}}

###

# @name get_elevenlabs_voices

GET {{baseURL}}/elevenlabs/v1/voices
xi-api-key: {{apikey}}

### 

# @name generate_tts

POST {{baseURL}}/elevenlabs/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM
Content-Type: application/json
xi-api-key: {{apikey}}

{
    "text": "Olá World!",
    "model_id": "eleven_multilingual_v2"

}