@baseURL = http://localhost:8000

# @name HealthCheck

GET {{baseURL}}/

###

# @name get_elevenlabs_voices

GET {{baseURL}}/elevenlabs/v1/voices

### 

# @name generate_tts

POST {{baseURL}}/elevenlabs/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM
Content-Type: application/json

{
    "text": "Olá World!",
    "model_id": "eleven_multilingual_v2"

}