# @baseURL = http://localhost:8000
@baseURL = https://aio.fly.dev
@apikey = {{$dotenv API_KEYS}}

# @name HealthCheck

GET {{baseURL}}/
xi-api-key: {{apikey}}

###

# @name get_elevenlabs_voices

GET {{baseURL}}/elevenlabs/v1/voices
xi-api-key: {{apikey}}

### 

# @name generate_tts

POST {{baseURL}}/elevenlabs/v1/text-to-speech/CYw3kZ02Hs0563khs1Fj
Content-Type: application/json
xi-api-key: {{apikey}}

{
    "text": "Hello World",
    "model_id": "eleven_multilingual_v2"
}

### 

# @name get_openai_manifest
GET {{baseURL}}/openai-plugin/.well-known/ai-plugin.json

### 

# @name get_openapi_plugin_manifest
GET {{baseURL}}/openai-plugin/.well-known/openapi.json

### 

# @name get_github_repository

GET {{baseURL}}/openai-plugin/github/repository/felippechemello/felippechemello
Authorization: Bearer {{apikey}}

###

# @name get_llm_models

GET {{baseURL}}/llm/v1/models
Authorization: Bearer {{apikey}}

###

# @name generate_completion

POST {{baseURL}}/llm/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{apikey}}

{
    "messages": [{"role": "user", "content": "Write a YouTube Script about nuclear fusion for a children's show."}],
    "model": "gpt-3.5-turbo-16k-0613"
}
