@baseURL = http://localhost:8000
# @baseURL = https://aio.fly.dev
@apikey = {{$dotenv API_KEYS}}

# @name HealthCheck

GET {{baseURL}}/
xi-api-key: {{apikey}}

###

# @name get_elevenlabs_voices

GET {{baseURL}}/elevenlabs/v1/voices
xi-api-key: {{apikey}}

### 

# @name generate_tts

POST {{baseURL}}/elevenlabs/v1/text-to-speech/CYw3kZ02Hs0563khs1Fj
Content-Type: application/json
xi-api-key: {{apikey}}

{
    "text": "Hello World",
    "model_id": "eleven_multilingual_v2"
}

### 

# @name tts_usage

GET {{baseURL}}/elevenlabs/usage
xi-api-key: {{apikey}}

### 

# @name get_openai_manifest
GET {{baseURL}}/openai-plugin/.well-known/ai-plugin.json

### 

# @name get_openapi_plugin_manifest
GET {{baseURL}}/openai-plugin/.well-known/openapi.json

### 

# @name get_github_repository

GET {{baseURL}}/openai-plugin/github/repository/felippechemello/felippechemello
Authorization: Bearer {{apikey}}

###

# @name get_llm_models

GET {{baseURL}}/llm/v1/models
Authorization: Bearer {{apikey}}

###

# @name generate_completion_open_ai

POST {{baseURL}}/llm/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{apikey}}

{
    "messages": [{"role": "user", "content": "Hello"}],
    "model": "gpt-3.5-turbo-16k-0613"
}

###

# @name generate_completion_anthropic

POST {{baseURL}}/llm/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{apikey}}

{
    "prompt": "\n\nHuman: Hello, who are you? \n\nAssistant:",
    "model": "claude-2.1"
}

###

# @name generate_image

POST {{baseURL}}/images/v1/images/generations
Content-Type: application/json
Authorization: Bearer {{apikey}}

{
    "prompt": "A painting of a Welsh Corgi"
}

###

# @name forced_alignment

POST {{baseURL}}/aeneas/align
Authorization: Bearer {{apikey}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

Você sabia que testes de sangue revolucionários para diagnosticar Alzheimer podem estar disponíveis em breve? Isso poderá transformar a maneira como lidamos com uma das doenças mais desafiadoras da atualidade.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="audio_file"; filename="audio.wav"
Content-Type: audio/wav

< /home/felippe/Projects/AIO-AllInOneAI/wavs/0.wav
------WebKitFormBoundary7MA4YWxkTrZu0gW--

